Test: Fix conversation notifications view model test
This failure is expected as the failure occurs because the
'pushNotificationsStatusUpdate' hasn't been configured during the test
setup phases.

For more details see 'NullPointerException' stacktrace below:

------------------------------------------------------------------------
source cannot be null
java.lang.NullPointerException: source cannot be null
    at androidx.lifecycle.MediatorLiveData.addSource
      (MediatorLiveData.java:87)
    at org.wordpress.android.ui.reader.viewmodels.
      ConversationNotificationsViewModel.init
      (ConversationNotificationsViewModel.kt:145)
    at org.wordpress.android.ui.reader.viewmodels.
      ConversationNotificationsViewModel.start
      (ConversationNotificationsViewModel.kt:72)
    at org.wordpress.android.ui.reader.viewmodels.
      ConversationNotificationsViewModelTest.setupObserversAndStart
      (ConversationNotificationsViewModelTest.kt:202)
    at org.wordpress.android.ui.reader.viewmodels.
      ConversationNotificationsViewModelTest.follow ui state is DISABLED
      on start(ConversationNotificationsViewModelTest.kt:62)
------------------------------------------------------------------------

PS: Still, it is a bit weird that this test failure only started to
occur after updating the AndroidX Lifecycle library to 2.5.1.