Downgrade ExoPlayer version to 2.9.3
Gutenberg editor uses reactive-native-video 5.0.2-wp-1 (See [1]) which internally uses ExoPlayer v2.9.3 (See [2])
This causes the below crash when when Guternberg editor is opened for a post and newer ExoPlayer (v2.13) is used in the native app:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayer$EventListener;
        at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:28)
```

This commit downgrades ExoPlayer version to 2.9.3 to prevent this crash.

 [1]: https://github.com/WordPress/gutenberg/blob/ca67d603637950bc08291ed9208a3f2d2e3e67c2/packages/react-native-editor/package.json#L73
 [2]:https://github.com/wordpress-mobile/react-native-video/blob/5.0.2-wp-1/android-exoplayer/build.gradle#L46