Build: Enable build config build feature for editor and wordpress
This is an AGP version '8.0' breaking change that changes the build
option default values, see build failure below:

------------------------------------------------------------------------

 > Task :libs:editor:compileDebugJavaWithJavac FAILED
   ...
 Note: Some input files use or override a deprecated API.
 Note: Recompile with -Xlint:deprecation for details.
 4 errors

 FAILURE: Build failed with an exception.

 * What went wrong:
 Execution failed for task ':libs:editor:compileDebugJavaWithJavac'.
 > Compilation failed; see the compiler error output for details.

------------------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':WordPress'.
> com.android.builder.errors.EvalIssueException: defaultConfig contains
 custom BuildConfig fields, but the feature is disabled.

------------------------------------------------------------------------

Explanation: "Starting with AGP 8.0, the default values for these flags
have changed to improve build performance. AGP 8.0 doesn't generate
'BuildConfig' by default. You need to specify this option using the DSL
in the projects where you need it."

For more info see: https://developer.android.com/build/releases/
gradle-plugin#default-changes