Deps: Remove unused tracks dependency from wordpress module
With that change, the 'Tracks' related included build configuration is
also removed because it anyway hasn't been working as expected since
'com.automattic.tracks:crashlogging' got added as an explicit and more
focused dependency into the 'WordPress' module.

Note that the 'com.automattic:Automattic-Tracks-Android' dependency is
also being used on the 'analytics' module, which means, that this
'Tracks' included build wasn't working as expected, not at least to
100%, even when it was initially introduced.

Related PRs:
- [Gradle] Added tracks to included_builds.gradle #20193
https://github.com/wordpress-mobile/WordPress-Android/pull/20193
- Bump Tracks to 5.0.0 #20733
https://github.com/wordpress-mobile/WordPress-Android/pull/20733

------------------------------------------------------------------------

FYI: If anyone tries to use 'Tracks' as an included build they will get
the below runtime exception when opening the app:

"java.lang.RuntimeException: Unable to get provider
io.sentry.android.core.SentryInitProvider:
java.lang.IllegalArgumentException: DSN is required. Use empty string or
set enabled to false in SentryOptions to disable SDK."