Test: Fix reader discover view model test
This failure is expected as the failure occurs because the
'preloadPostEvents' wasn't being configured during the test
setup phases. For more details see 'NullPointerException' stacktrace
below:

------------------------------------------------------------------------
source cannot be null
java.lang.NullPointerException: source cannot be null
    at androidx.lifecycle.MediatorLiveData.addSource
      (MediatorLiveData.java:87)
    at org.wordpress.android.ui.reader.discover.
      ReaderDiscoverViewModel.init(ReaderDiscoverViewModel.kt:162)
    at org.wordpress.android.ui.reader.discover.
      ReaderDiscoverViewModel.start(ReaderDiscoverViewModel.kt:109)
    at org.wordpress.android.ui.reader.discover.
      ReaderDiscoverViewModelTest.init(ReaderDiscoverViewModelTest
     .kt:632)
    at org.wordpress.android.ui.reader.discover.
      ReaderDiscoverViewModelTest.initial uiState is loading
      (ReaderDiscoverViewModelTest.kt:200)
------------------------------------------------------------------------

PS: Still, it is a bit weird that this test failure only started to
occur after updating the AndroidX Lifecycle library to 2.5.1.