Update Kotlin [1.3.50 -> 1.3.61], coroutines [1.3.1 -> 1.3.3].
Fixes
IllegalStateException: Module with the Main dispatcher is missing.
https://git.io/JvUHp