Fix: Resolve lateinit property lifecycle registry not init crashes
Crash Message: "kotlin.UninitializedPropertyAccessException: lateinit
property lifecycleRegistry has not been initialized"

Below is one example of such crash on 'PhotoPickerActionModeCallback'
(out of the total 4) for when the user is trying to choose media while
creating a story.

The other 3 crashes that got resolved were related to:
- MediaPickerActionModeCallback: When the user is trying to choose photo
while adding images to a post.
- CommentListActionModeCallback: When the user is selecting multiple
comments to moderate.
- PreferenceFragmentLifeCycleOwner: When the user is trying to enter the
account settings screen.

------------------------------------------------------------------------
E  FATAL EXCEPTION: main
   Process: com.jetpack.android.beta, PID: 20301
   kotlin.UninitializedPropertyAccessException: lateinit property
    lifecycleRegistry has not been initialized
     at org.wordpress.android.ui.photopicker
      .PhotoPickerActionModeCallback.<init>
      (PhotoPickerActionModeCallback.kt:78)
     at org.wordpress.android.ui.photopicker
      .PhotoPickerFragment$observeUIState$1.invoke(PhotoPickerFragment
      .kt:200)
     at org.wordpress.android.ui.photopicker
      .PhotoPickerFragment$observeUIState$1.invoke(PhotoPickerFragment
      .kt:191)
     at org.wordpress.android.ui.photopicker
      .PhotoPickerFragment$sam$androidx_lifecycle_Observer$0.onChanged
      (Unknown Source:2)
------------------------------------------------------------------------

In order to resolve these 3 x 'XyzActionModeCallback' and this single
'PreferenceFragmentLifeCycleOwner' lateinit property 'lifecycleRegistry'
has not been initialized related crashes (4 in total), the lateinit
'lifecycleRegistry' property got replaced with a 'val' such equivalent.

FYI: This single 'PreferenceFragmentLifeCycleOwner' class, all those
3 x 'XyzActionModeCallback' classes, along with the 'LiveDataUtils'
utility class need to be replaced with a more modern approach in order
to avoid any future such surprises.