Build: Update sentry plugin to 3.5.0
Release Notes: https://github.com/getsentry/
sentry-android-gradle-plugin/releases/tag/3.5.0

------------------------------------------------------------------------

Updating Sentry plugin to '3.5.0' solves the below UI related test
failure that is closely related the 'Lifecycle' update to '2.6.1':

E  FATAL EXCEPTION: main
   Process: com.jetpack.android.beta, PID: 20928
   java.lang.NullPointerException: Parameter specified as non-null is
    null: method androidx.lifecycle.LifecycleRegistry.removeObserver,
    parameter observer
     at androidx.lifecycle.LifecycleRegistry.removeObserver(Unknown
      Source:3)
     at io.sentry.android.core.AppLifecycleIntegration.removeObserver
      (AppLifecycleIntegration.java:97)
     at io.sentry.android.core.AppLifecycleIntegration
      .lambda$close$1$io-sentry-android-core-AppLifecycleIntegration
      (AppLifecycleIntegration.java:108)
     at io.sentry.android.core
      .AppLifecycleIntegration$$ExternalSyntheticLambda0.run(Unknown
      Source:2)
     at android.os.Handler.handleCallback(Handler.java:942)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loopOnce(Looper.java:201)
     at android.os.Looper.loop(Looper.java:288)
     at android.app.ActivityThread.main(ActivityThread.java:7898)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
      (RuntimeInit.java:548)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)