Analysis: Create missing switch cases for store actions
Error: "'switch' statement on enum type
'org.wordpress.android.fluxc.action.TaxonomyAction' misses cases:
'UPDATE_TERM', and 'REMOVE_TERM'"