Update Kotlin [1.3.11 -> 1.3.61], coroutines [1.1.0 -> 1.3.3].
Fixes
IllegalStateException: Module with the Main dispatcher is missing.
https://git.io/JvUHp