fix: DocsBot initialization (#21755)
The previous `getQueryParams` implementation created an object with
key-value pairs, where each value was an array of a single string. This
appears unnecessary as each DocsBot configuration option expects a
string, not an array.

Seemingly, the previous implementation worked because:

First, we invoke `decodeURIComponent` on most options before passing
them to DocsBot, which performs an implicit type coercion from array to
string.

Second, we rely upon a remote `https://widget.docsbot.ai/chat.js`
script. Presumably, this remote script was performing implicit type
coercions on our behalf, but may have recently updated to no longer do
so. This resulted in new failures when attempting to invoke string
methods on an array:

```
[INFO:CONSOLE(44)] "Uncaught (in promise) TypeError: i.id.split is not a function", source: https://widget.docsbot.ai/chat.js (44)
```

From reviewing our WP-iOS implementation, it initializes DocsBot with
string values, not arrays, further affirming this new approach.